name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        lfs: true
    - name: Install nightly rustfmt
      run: rustup toolchain install nightly --component rustfmt --profile minimal
    - name: Check Fmt (nightly)
      run: cargo +nightly fmt --check --verbose
    - name: Build (check)
      run: cargo check
    - name: Clippy
      run: cargo clippy -- -D warnings
    - name: Run tests 
      run: cargo test
